### PR TITLE
Proposal for CI actions workflow.

### PR DESCRIPTION
**Pull request by cusma**
Proposal for CI workflow including:

1. `poetry` for packaging and dependencies management
2. `per-commit` for formatting checks
3. `pytest` + `sandbox` for unit-tests and end-to-end tests

### CODE REVIEW

**Review by barnjamin — APPROVED** [review]

**Review by tzaffi — APPROVED** [review]
Starting off - LGTM

**Comment by tzaffi** [comment]
...but should definitely pass tests before merging

**Comment by cusma** [comment]
> ...but should definitely pass tests before merging

Sure! Passing now after some minor fixes!

**Comment by cusma** [comment]
Awesome! Thanks @barnjamin and @tzaffi

**Comment by aorumbayev** [comment]
Awesome @cusma glad that you guys found the ci setup useful 🙂👍

**Pull request merged**
